# Generated by Django 5.2.1 on 2025-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
