# Generated by Django 5.2 on 2025-06-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0003_investimento_ampliacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investimento_ampliacoes',
            new_name='Ampliacoes',
        ),
    ]
