# Generated by Django 5.2 on 2025-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0003_remove_custoproducao_materia_prima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoproducao',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
