# Generated by Django 5.2 on 2025-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0004_rename_investimento_ampliacoes_ampliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliacoes',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
