# Generated by Django 5.2 on 2025-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0004_custoproducao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
