# Generated by Django 5.2 on 2025-06-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0005_alter_ampliacoes_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('terceiros', 'Produto de terceiros'), ('fabricacao', 'Fabricação própria')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('unidade_venda', models.CharField(max_length=20)),
                ('margem_lucro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_varia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='planodenegocios.produtoservico')),
            ],
        ),
    ]
