# Generated by Django 5.2 on 2025-06-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0005_alter_ampliacoes_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('salario_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodenegocios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20)),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodenegocios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodenegocios.funcionario')),
            ],
        ),
    ]
