# Generated by Django 5.2 on 2025-08-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0005_produtoservico_preco_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoproducao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='planodenegocios.produtoservico'),
        ),
    ]
