# Generated by Django 5.2 on 2025-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0006_funcionario_encargo_beneficio_salariomensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EncargoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
