# Generated by Django 5.2 on 2025-08-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0006_alter_custoproducao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoproducao',
            name='materia_prima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='embalagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
