# Generated by Django 5.2 on 2025-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0006_produtoservico_custoproducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoservico',
            name='preco_varia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
