# Generated by Django 5.2 on 2025-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0007_alter_produtoservico_preco_varia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custoproducao',
            old_name='nome',
            new_name='embalagem',
        ),
        migrations.RemoveField(
            model_name='custoproducao',
            name='custo_unitario',
        ),
        migrations.AddField(
            model_name='custoproducao',
            name='frete',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
