# Generated by Django 5.2 on 2025-08-11 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0007_custoproducao_materia_prima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoservico',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
