# Generated by Django 5.2 on 2025-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0008_rename_nome_custoproducao_embalagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoproducao',
            name='embalagem',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='frete',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
