# Generated by Django 5.2 on 2025-08-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0009_alter_produtoservico_margem_lucro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='custo_unitario',
            field=models.FloatField(default=0),
        ),
    ]
