# Generated by Django 5.2 on 2025-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0009_alter_custoproducao_embalagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoproducao',
            name='produto',
            field=models.CharField(max_length=255),
        ),
    ]
