# Generated by Django 5.2 on 2025-06-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0010_alter_custoproducao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoproducao',
            name='embalagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='planodenegocios.produtoservico'),
        ),
    ]
