# Generated by Django 5.2 on 2025-07-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0011_posicionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocoSegmentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Foco e Segmentação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
