# Generated by Django 5.2 on 2025-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0012_empresa_socio_distribuicaolucro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
