# Generated by Django 5.2 on 2025-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0013_remove_custoproducao_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custoproducao',
            name='custo_unitario',
        ),
        migrations.RemoveField(
            model_name='custoproducao',
            name='produto_servico',
        ),
        migrations.AddField(
            model_name='custoproducao',
            name='produto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
