# Generated by Django 5.2 on 2025-07-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0007_despesamensal_encargoglobal'),
        ('planodenegocios', '0014_remove_custoproducao_custo_unitario_and_more'),
    ]

    operations = [
    ]
