# Generated by Django 5.2 on 2025-07-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0015_produtosservicosinsumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoLegalEstruturaSocietaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Descrição Legal e Estrutura Societária')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
