# Generated by Django 5.2 on 2025-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0025_alternativasestrategicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaadministrativa',
            name='mes',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
    ]
