# Generated by Django 5.2 on 2025-07-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0026_despesaadministrativa_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodenegocios.despesaadministrativa')),
            ],
        ),
    ]
