# Generated by Django 5.2 on 2025-07-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0027_creditotributario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceiro', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
            ],
        ),
    ]
