# Generated by Django 5.2 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0027_creditotributario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do sócio')),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoLucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor inicial (mês 1)')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_lucro', to='planodenegocios.empresa')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='planodenegocios.socio', verbose_name='Sócio')),
            ],
            options={
                'verbose_name': 'Remuneração dos Sócios – Lucros e Dividendos',
                'verbose_name_plural': 'Remuneração dos Sócios – Lucros e Dividendos',
            },
        ),
        migrations.CreateModel(
            name='ValorMensalDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('constante', models.BooleanField(default=True)),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_mensais', to='planodenegocios.distribuicaolucro')),
            ],
            options={
                'verbose_name': 'Valor Mensal da Distribuição',
                'verbose_name_plural': 'Valores Mensais das Distribuições',
            },
        ),
    ]
