# Generated by Django 5.2 on 2025-07-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0028_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
            ],
        ),
        migrations.DeleteModel(
            name='Prestador',
        ),
    ]
