# Generated by Django 5.2 on 2025-07-29 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0029_terceiro_delete_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemuneracaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Mês 1'), (2, 'Mês 2'), (3, 'Mês 3'), (4, 'Mês 4'), (5, 'Mês 5'), (6, 'Mês 6'), (7, 'Mês 7'), (8, 'Mês 8'), (9, 'Mês 9'), (10, 'Mês 10'), (11, 'Mês 11'), (12, 'Mês 12')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodenegocios.terceiro')),
            ],
        ),
    ]
