# Generated by Django 5.2 on 2025-07-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0030_remuneracaomensal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceiro',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='terceiro',
            name='valor_inicial',
        ),
        migrations.DeleteModel(
            name='RemuneracaoMensal',
        ),
    ]
