# Generated by Django 5.2 on 2025-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0031_remove_terceiro_mes_remove_terceiro_valor_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoproducao',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
