# Generated by Django 5.2 on 2025-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planodenegocios', '0033_alter_custoproducao_custo_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custoproducao',
            name='custo_unitario',
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='embalagem',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='frete',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custoproducao',
            name='produto',
            field=models.CharField(max_length=255),
        ),
    ]
